version: "3.8"
services:
  infisical:
    container_name: infisical
    env_file:
      - .env
    ports:
      - 66:8080
    image: infisical/infisical:latest
  mongo:
    container_name: infisical-mongo
    image: mongo:4.4.27
    restart: always
    env_file:
      - .env
    volumes:
      - infisical-mongo:/data/db
  redis:
    container_name: infisical-redis
    image: redis:7.2.3
    restart: always
    env_file:
      - .env
    volumes:
      - infisical-redis:/data
volumes:
  infisical-mongo:
  infisical-redis:
